### ISSUE TITLE
Prepare Jakarta Expression Language for Jakarta EE 8 Release

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/el-ri#87]
### Tasks

- [x] Update text files
- [x] Generate "boilerplate" specification project
- [x] Make a staging release
- [x] Generate Stand-alone TCK test results
- [x] Create a PR to jakartaee/specifications project
- [x] Update the Jakarta EE API jar by submitting a PR to the [jakartaee-api](https://github.com/eclipse-ee4j/jakartaee-api) project

See [here](https://wiki.eclipse.org/How_to_Prepare_API_Projects_to_Jakarta_EE_8_Release) for detailed instructions.

**Comment by arjantijms** [comment]
API jar staged at: https://oss.sonatype.org/content/repositories/staging/jakarta/el/jakarta.el-api/3.0.3/

**Comment by arjantijms** [comment]
Combined jar staged at: [jakarta.el](https://oss.sonatype.org/content/repositories/staging/org/glassfish/jakarta.el/3.0.3/)

TCK run: [summary.tx](https://jenkins.eclipse.org/el/job/2_expression-language-run-tck-against-staged-build/lastSuccessfulBuild/artifact/eltck/bin/summary.txt/*view*/)

**Comment by m0mus** [comment]
Reopening because new tasks were added.

**Comment by arjantijms** [comment]
[API PR](https://github.com/eclipse-ee4j/jakartaee-api/pull/17)

**Comment by arjantijms** [comment]
[Github pages requested](https://bugs.eclipse.org/bugs/show_bug.cgi?id=549723)
